# Generated by Django 3.1.7 on 2021-04-07 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20210407_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='item_done',
            field=models.CharField(default=django.utils.timezone.now, max_length=4, verbose_name='Item Done'),
            preserve_default=False,
        ),
    ]
